"""Minimal type stubs for ``requests.exceptions``.

Only the classes ``agm.core.http`` classifies transport failures against are
typed, each with a plain ``__init__`` so isinstance checks and class
references stay free of ``Any`` (the real classes take ``*args: Any,
**kwargs: Any``, which taints both).
"""

from requests.models import Response

class RequestException(IOError):
    response: Response | None
    def __init__(
        self, *args: object, response: Response | None = ..., request: object = ...
    ) -> None: ...

class ConnectionError(RequestException): ...
class SSLError(ConnectionError): ...
class Timeout(RequestException): ...
class TooManyRedirects(RequestException): ...
class MissingSchema(RequestException, ValueError): ...
class InvalidSchema(RequestException, ValueError): ...
class InvalidURL(RequestException, ValueError): ...
class InvalidHeader(RequestException, ValueError): ...
