"""Public match-compilation artifacts, diagnostics, and decision contract.

Matrix construction, normalization, allocation, provenance, and compiler
helpers are implementation details available only from their defining
submodules.
"""

from .compiler import CompiledMatchSite
from .diagnostics import (
    BoolWitness,
    EnumWitness,
    EnumWitnessQualification,
    LiteralWitness,
    MatchIssue,
    MatchWitness,
    NonExhaustiveIssue,
    OpenComplementWitness,
    RecordWitness,
    RedundantArmIssue,
    RefutableLetIssue,
    WildcardWitness,
    WitnessField,
    render_witness,
)
from .model import (
    BoolConstructor,
    CaseSite,
    Constructor,
    Decision,
    DecisionDecompose,
    DecisionLeaf,
    DecisionSwitch,
    EnumConstructor,
    FieldOccurrenceProvenance,
    LetBindingAction,
    LetSite,
    LiteralKind,
    MatchSiteSource,
    NormalizedMatchSite,
    Occurrence,
    OccurrenceId,
    RecordConstructor,
)
from .stage import (
    MatchCompilationResult,
    MatchCompiledArtifact,
    MatchCompiledModule,
    MatchCompiledProgram,
    compile_program_matches,
    diagnostic_from_match_issue,
    diagnostics_from_match_issues,
    validate_match_compiled_module,
    validate_match_compiled_program,
)

__all__ = [
    "BoolConstructor",
    "BoolWitness",
    "Constructor",
    "CompiledMatchSite",
    "CaseSite",
    "Decision",
    "DecisionDecompose",
    "DecisionLeaf",
    "DecisionSwitch",
    "EnumConstructor",
    "EnumWitness",
    "FieldOccurrenceProvenance",
    "EnumWitnessQualification",
    "LetBindingAction",
    "LetSite",
    "LiteralKind",
    "LiteralWitness",
    "MatchCompilationResult",
    "MatchCompiledArtifact",
    "MatchCompiledProgram",
    "MatchCompiledModule",
    "MatchIssue",
    "MatchSiteSource",
    "MatchWitness",
    "NonExhaustiveIssue",
    "NormalizedMatchSite",
    "Occurrence",
    "OccurrenceId",
    "OpenComplementWitness",
    "RecordConstructor",
    "RecordWitness",
    "RedundantArmIssue",
    "RefutableLetIssue",
    "WildcardWitness",
    "WitnessField",
    "compile_program_matches",
    "diagnostic_from_match_issue",
    "diagnostics_from_match_issues",
    "render_witness",
    "validate_match_compiled_program",
    "validate_match_compiled_module",
]
