"""Public API for the AgL v2 AST package (agm.agl.syntax).

This package is the *firewall* between the Lark-aware front-end (lexer +
parser) and all downstream passes (scope, typecheck, eval).  Nothing in this
package imports Lark or any other AgL-internal module except ``spans``.

Usage::

    from agm.agl.syntax import Program, LetDecl, VarRef, walk
"""

from __future__ import annotations

from agm.agl.syntax.nodes import (
    ELSE,
    AgentDecl,
    BinaryOp,
    Binder,
    BinOp,
    Block,
    BoolLit,
    Call,
    Case,
    CaseBranch,
    CatchClause,
    ConfigPragma,
    Constructor,
    ConstructorPattern,
    DecimalLit,
    Declaration,
    DictEntry,
    DictLit,
    Do,
    ElseSentinel,
    EnumDef,
    Expr,
    FieldAccess,
    FieldDef,
    FuncDef,
    If,
    IfBranch,
    IndexAccess,
    IndexTarget,
    InterpSegment,
    IntLit,
    IsTest,
    Item,
    Lambda,
    LetDecl,
    ListLit,
    LiteralPattern,
    NamedArg,
    NameTarget,
    NullLit,
    Param,
    ParamDecl,
    Pattern,
    PatternField,
    PragmaValue,
    Program,
    ProgramDecl,
    Raise,
    RecordDef,
    SetStmt,
    SetTarget,
    StringLit,
    Template,
    TemplateSegment,
    TextSegment,
    Try,
    TypeAlias,
    UnaryNeg,
    UnaryNot,
    UnitLit,
    VarDecl,
    VariantDef,
    VarPattern,
    VarRef,
    WildcardPattern,
    set_target_root_name,
)
from agm.agl.syntax.spans import SourceSpan
from agm.agl.syntax.types import (
    AgentT,
    BoolT,
    DecimalT,
    DictT,
    FuncT,
    IntT,
    JsonT,
    ListT,
    NameT,
    TextT,
    TypeExpr,
    UnitT,
)
from agm.agl.syntax.visitor import Visitor, walk

__all__ = [
    # spans
    "SourceSpan",
    # type exprs
    "TextT",
    "JsonT",
    "BoolT",
    "IntT",
    "DecimalT",
    "NameT",
    "ListT",
    "DictT",
    "UnitT",
    "AgentT",
    "FuncT",
    "TypeExpr",
    # program
    "Program",
    # declarations
    "FuncDef",
    "RecordDef",
    "EnumDef",
    "TypeAlias",
    "ParamDecl",
    "ProgramDecl",
    "AgentDecl",
    "FieldDef",
    "VariantDef",
    "ConfigPragma",
    "PragmaValue",
    # binders
    "LetDecl",
    "VarDecl",
    "SetStmt",
    "NameTarget",
    "IndexTarget",
    "SetTarget",
    "set_target_root_name",
    # expressions
    "Block",
    "VarRef",
    "FieldAccess",
    "IndexAccess",
    "Constructor",
    "NamedArg",
    "BinaryOp",
    "BinOp",
    "UnaryNot",
    "UnaryNeg",
    "IsTest",
    "Call",
    "Param",
    "Lambda",
    "If",
    "IfBranch",
    "Case",
    "CaseBranch",
    "Do",
    "Try",
    "CatchClause",
    "Raise",
    "UnitLit",
    "IntLit",
    "DecimalLit",
    "BoolLit",
    "NullLit",
    "StringLit",
    "ListLit",
    "DictLit",
    "DictEntry",
    "Template",
    "TextSegment",
    "InterpSegment",
    # patterns
    "WildcardPattern",
    "LiteralPattern",
    "VarPattern",
    "ConstructorPattern",
    "PatternField",
    # sentinel
    "ELSE",
    "ElseSentinel",
    # union aliases
    "Expr",
    "Binder",
    "Declaration",
    "Item",
    "Pattern",
    "TemplateSegment",
    # visitor
    "Visitor",
    "walk",
]
