from __future__ import annotations

from collections.abc import Iterator


class Item:
    @property
    def value(self) -> object: ...
    def unwrap(self) -> object: ...
    def as_string(self) -> str: ...


class Table(Item):
    def __contains__(self, key: object) -> bool: ...
    def __getitem__(self, key: str) -> Item: ...
    def __setitem__(self, key: str, value: object) -> None: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...
    def get(self, key: str, default: object = ...) -> Item | None: ...
    def add(self, key: str, value: object) -> None: ...
    def items(self) -> list[tuple[str, Item]]: ...
    def keys(self) -> list[str]: ...
    def values(self) -> list[Item]: ...
    def unwrap(self) -> dict[str, object]: ...
    def append(self, key: str | None, value: object) -> Table: ...


class InlineTable(Item):
    def __contains__(self, key: object) -> bool: ...
    def __getitem__(self, key: str) -> Item: ...
    def __setitem__(self, key: str, value: object) -> None: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...
    def get(self, key: str, default: object = ...) -> Item | None: ...
    def items(self) -> list[tuple[str, Item]]: ...
    def keys(self) -> list[str]: ...
    def values(self) -> list[Item]: ...
    def unwrap(self) -> dict[str, object]: ...
