from __future__ import annotations

from collections.abc import Iterator
from tomlkit.items import Item, Table


class TOMLDocument:
    def __contains__(self, key: object) -> bool: ...
    def __getitem__(self, key: str) -> Item: ...
    def __setitem__(self, key: str, value: object) -> None: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...
    def get(self, key: str, default: object = ...) -> Item | None: ...
    def add(self, key: str, value: object) -> None: ...
    def items(self) -> list[tuple[str, Item]]: ...
    def keys(self) -> list[str]: ...
    def values(self) -> list[Item]: ...
    def unwrap(self) -> dict[str, object]: ...
