"""AgL typeless execution IR — public surface.

This package contains the immutable data model for the execution IR emitted
by the lowering/linking phase (M2+) and consumed by the new evaluator (M2+).

The IR carries no checker ``Type``, ``TypeEnvironment``, ``FunctionSignature``,
``CastSpec``, type expression, or ``node_types``/``binding_types`` table.

Imports: only stdlib and ``agm.agl.modules.ids``.  No eval, runtime, values,
syntax, scope, or typecheck imports are permitted in this package.

``__all__`` is sorted and complete (all public names re-exported here).
"""

from __future__ import annotations

from agm.agl.ir.ids import (
    ContractId,
    FunctionId,
    Location,
    NominalId,
    SourceId,
    SymbolId,
)
from agm.agl.ir.nodes import (
    IrAnd,
    IrArith,
    IrAssign,
    IrBind,
    IrBlock,
    IrCoerce,
    IrCompare,
    IrConstBool,
    IrConstDecimal,
    IrConstInt,
    IrConstJsonNull,
    IrConstText,
    IrConstUnit,
    IrContains,
    IrExpr,
    IrField,
    IrIndex,
    IrIndexStep,
    IrLoad,
    IrMakeDict,
    IrMakeList,
    IrOr,
    IrRenderTemplate,
    IrSequence,
    IrTemplateSegment,
    IrTemplateText,
    IrTemplateValue,
    IrUnary,
)
from agm.agl.ir.operations import (
    ArithKind,
    ArithOp,
    CmpOp,
    Coercion,
    CompareKind,
    ContainsKind,
    IndexKind,
    IntToDecimal,
    MapDictValues,
    MapEnumFields,
    MapList,
    MapRecordFields,
    NumericKind,
    ToJson,
    UnaryOp,
)
from agm.agl.ir.program import (
    ExecutableModule,
    ExecutableProgram,
    NominalDescriptor,
    NominalKind,
    SourceFile,
    SymbolDescriptor,
)
from agm.agl.ir.validate import InvalidIrError, validate_ir

__all__ = [
    "ArithKind",
    "ArithOp",
    "CmpOp",
    "Coercion",
    "CompareKind",
    "ContainsKind",
    "ContractId",
    "ExecutableModule",
    "ExecutableProgram",
    "FunctionId",
    "IndexKind",
    "IntToDecimal",
    "InvalidIrError",
    "IrAnd",
    "IrArith",
    "IrAssign",
    "IrBind",
    "IrBlock",
    "IrCoerce",
    "IrCompare",
    "IrConstBool",
    "IrConstDecimal",
    "IrConstInt",
    "IrConstJsonNull",
    "IrConstText",
    "IrConstUnit",
    "IrContains",
    "IrExpr",
    "IrField",
    "IrIndex",
    "IrIndexStep",
    "IrLoad",
    "IrMakeDict",
    "IrMakeList",
    "IrOr",
    "IrRenderTemplate",
    "IrSequence",
    "IrTemplateSegment",
    "IrTemplateText",
    "IrTemplateValue",
    "IrUnary",
    "Location",
    "MapDictValues",
    "MapEnumFields",
    "MapList",
    "MapRecordFields",
    "NominalDescriptor",
    "NominalId",
    "NominalKind",
    "NumericKind",
    "SourceFile",
    "SourceId",
    "SymbolDescriptor",
    "SymbolId",
    "ToJson",
    "UnaryOp",
    "validate_ir",
]
