"""AgL typeless execution IR — public surface.

This package contains the immutable data model for the execution IR emitted
by the lowering/linking phase and consumed by the evaluator.

The IR carries no checker ``Type``, ``TypeEnvironment``, ``FunctionSignature``,
``CastSpec``, type expression, or ``node_types``/``binding_types`` table.

Imports: only stdlib and ``agm.agl.modules.ids``.  No eval, runtime, values,
syntax, scope, or typecheck imports are permitted in this package.

``__all__`` is sorted and complete (all public names re-exported here).
"""

from __future__ import annotations

from agm.agl.ir.contracts import (
    ConversionFailureMode,
    ConversionRecipe,
    ConversionStrategy,
    DecodeSchema,
    DictDecode,
    EnumDecode,
    ListDecode,
    RecordDecode,
    ScalarDecode,
    ScalarKind,
    VariantDecode,
)
from agm.agl.ir.ids import (
    ContractId,
    FunctionId,
    Location,
    NominalId,
    SourceId,
    SymbolId,
)
from agm.agl.ir.nodes import (
    AutoTraceField,
    IrAnd,
    IrArith,
    IrAssign,
    IrBind,
    IrBindPlan,
    IrBlock,
    IrCapture,
    IrCase,
    IrCaseArm,
    IrCatchHandler,
    IrCoerce,
    IrCompare,
    IrConstBool,
    IrConstDecimal,
    IrConstInt,
    IrConstJsonNull,
    IrConstructorPlan,
    IrConstText,
    IrConstUnit,
    IrContains,
    IrConvert,
    IrDirectCall,
    IrExec,
    IrExpr,
    IrField,
    IrFunctionParam,
    IrIf,
    IrIfBranch,
    IrIndex,
    IrIndexStep,
    IrIndirectCall,
    IrLiteralPlan,
    IrLoad,
    IrLoop,
    IrMakeClosure,
    IrMakeConstructor,
    IrMakeDict,
    IrMakeEnum,
    IrMakeException,
    IrMakeList,
    IrMakeRecord,
    IrMatchPlan,
    IrOr,
    IrParseJson,
    IrPrint,
    IrRaise,
    IrRenderTemplate,
    IrSequence,
    IrTemplateSegment,
    IrTemplateText,
    IrTemplateValue,
    IrTry,
    IrUnary,
    IrVariantIs,
    IrVariantPlan,
    IrWildcardPlan,
    UseDefault,
)
from agm.agl.ir.operations import (
    ArithKind,
    ArithOp,
    CmpOp,
    Coercion,
    CompareKind,
    ContainsKind,
    IndexKind,
    IntToDecimal,
    MapDictValues,
    MapEnumFields,
    MapList,
    MapRecordFields,
    NumericKind,
    ToJson,
    UnaryOp,
)
from agm.agl.ir.program import (
    DryRunEntry,
    ExecutableModule,
    ExecutableProgram,
    FunctionDescriptor,
    IrParam,
    NominalDescriptor,
    NominalKind,
    SourceFile,
    SymbolDescriptor,
    VariantDescriptor,
)
from agm.agl.ir.validate import InvalidIrError, validate_ir

__all__ = [
    "ArithKind",
    "ArithOp",
    "AutoTraceField",
    "CmpOp",
    "Coercion",
    "CompareKind",
    "ContainsKind",
    "ContractId",
    "ConversionFailureMode",
    "ConversionRecipe",
    "ConversionStrategy",
    "DecodeSchema",
    "DictDecode",
    "DryRunEntry",
    "EnumDecode",
    "ExecutableModule",
    "ExecutableProgram",
    "FunctionDescriptor",
    "FunctionId",
    "IndexKind",
    "IntToDecimal",
    "InvalidIrError",
    "IrAnd",
    "IrArith",
    "IrAssign",
    "IrBind",
    "IrBindPlan",
    "IrBlock",
    "IrCapture",
    "IrCase",
    "IrCaseArm",
    "IrCatchHandler",
    "IrCoerce",
    "IrCompare",
    "IrConstBool",
    "IrConstDecimal",
    "IrConstInt",
    "IrConstJsonNull",
    "IrConstText",
    "IrConstUnit",
    "IrConstructorPlan",
    "IrContains",
    "IrConvert",
    "IrDirectCall",
    "IrExec",
    "IrExpr",
    "IrField",
    "IrFunctionParam",
    "IrIf",
    "IrIfBranch",
    "IrIndex",
    "IrIndexStep",
    "IrIndirectCall",
    "IrLiteralPlan",
    "IrLoad",
    "IrLoop",
    "IrMakeClosure",
    "IrMakeConstructor",
    "IrMakeDict",
    "IrMakeEnum",
    "IrMakeException",
    "IrMakeList",
    "IrMakeRecord",
    "IrMatchPlan",
    "IrOr",
    "IrParam",
    "IrParseJson",
    "IrPrint",
    "IrRaise",
    "IrRenderTemplate",
    "IrSequence",
    "IrTemplateSegment",
    "IrTemplateText",
    "IrTemplateValue",
    "IrTry",
    "IrUnary",
    "IrVariantIs",
    "IrVariantPlan",
    "IrWildcardPlan",
    "ListDecode",
    "Location",
    "MapDictValues",
    "MapEnumFields",
    "MapList",
    "MapRecordFields",
    "NominalDescriptor",
    "NominalId",
    "NominalKind",
    "NumericKind",
    "RecordDecode",
    "ScalarDecode",
    "ScalarKind",
    "SourceFile",
    "SourceId",
    "SymbolDescriptor",
    "SymbolId",
    "ToJson",
    "UnaryOp",
    "UseDefault",
    "VariantDecode",
    "VariantDescriptor",
    "validate_ir",
]
