class CommandNotFound(Exception):
    program: str
    path: str
    def __init__(self, program: str, path: str | None = None) -> None: ...

class BoundCommand:
    executable: str
    def __init__(self, executable: str, args: tuple[str, ...] = ()) -> None: ...
    def __getitem__(self, args: object) -> BoundCommand: ...
    @property
    def formulate(self) -> list[str]: ...

class LocalMachine:
    def __getitem__(self, cmd: str) -> BoundCommand: ...
